root = "."
tmp_dir = "bin"

[build]
cmd = "make"
bin = "bin/mdpages"
full_bin = "APP_ENV=dev APP_USER=air ./bin/mdpages"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "bin", "docs"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true