// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/yosa12978/mdpages/types"

func Signup(data types.TemplData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n        var check = function() {\n            if (document.getElementById('password').value !=\n                document.getElementById('confirm_password').value) {\n                document.getElementById('message').style.color = 'red';\n                document.getElementById('message').innerHTML = 'Passwords do not match<br>';\n                document.getElementById('submit').disabled = true;\n            } else {\n                document.getElementById('message').style.color = 'green';\n                document.getElementById('message').innerHTML = '';\n                document.getElementById('submit').disabled = false;\n            }\n        }\n        </script> <h1 class=\"mb-2\">Signup</h1><form hx-post=\"/htmx/signup\" hx-target=\"#red-box\" hx-swap=\"innerHTML\" hx-ext=\"json-enc\" style=\"max-width:500px;\"><div id=\"red-box\" class=\"alert alert-danger border border-4 border-danger\"></div><label>Username</label> <input type=\"text\" name=\"username\" class=\"form-control mb-2\" placeholder=\"username\"> <label>Password</label> <input type=\"password\" name=\"password\" class=\"form-control mb-2\" id=\"password\" onkeyup=\"check();\" placeholder=\"password\"> <label>Confirm password</label> <input type=\"password\" name=\"confirm_password\" class=\"form-control mb-2\" id=\"confirm_password\" onkeyup=\"check();\" placeholder=\"confirm password\"> <span id=\"message\" class=\"text-danger\"></span> <button type=\"submit\" id=\"submit\" class=\"btn btn-outline-dark\">Signup</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
