// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Signup() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n        var check = function() {\n            if (document.getElementById('password').value !=\n                document.getElementById('confirm_password').value) {\n                document.getElementById('message').style.color = 'red';\n                document.getElementById('message').innerHTML = 'Passwords do not match<br>';\n                document.getElementById('submit').disabled = true;\n            } else {\n                document.getElementById('message').style.color = 'green';\n                document.getElementById('message').innerHTML = '';\n                document.getElementById('submit').disabled = false;\n            }\n        }\n        </script> <h1>Signup</h1><form method=\"POST\" action=\"/htmx/signup\" style=\"max-width:500px;\"><label class=\"mt-2\">Username</label> <input type=\"text\" name=\"username\" class=\"form-control\" placeholder=\"username\"> <label class=\"mt-2\">Password</label> <input type=\"password\" name=\"password\" class=\"form-control\" id=\"password\" onkeyup=\"check();\" placeholder=\"password\"> <label class=\"mt-2\">Confirm password</label> <input type=\"password\" name=\"confirm_password\" class=\"form-control\" id=\"confirm_password\" onkeyup=\"check();\" placeholder=\"confirm password\"> <span id=\"message\" class=\"\"></span> <button type=\"submit\" id=\"submit\" class=\"btn btn-outline-dark mt-2\">Signup</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base("mdpages - Signup").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
